version: 2

models:
  - name: stg_orders
    description: "Order Staging - Clean Data"
    columns:
      - name: order_id
        description: "Order Primary key"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "FK a customers"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: total_amount
        description: "Total Amount of the order"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_customers
    description: "Staging de clientes - datos limpios"
    columns:
      - name: customer_id
        description: "Primary key de cliente"
        tests:
          - unique
          - not_null
      - name: customer_email
        description: "Email único por cliente"
        tests:
          - unique
          - not_null

  - name: stg_products
    description: "Products Staging - Clean Data"
    columns:
      - name: product_id
        description: "Product Primary key"
        tests:
          - unique
          - not_null
      - name: price
        description: "Product price"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
